title: Meru Data
email: info@merudata.com
url: "https://proud-bush-09c843910.1.azurestaticapps.net/docs"
twitter_username: merudata
github_username:  merudata
baseurl: "/docs"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-relative-links
relative_links:
  enabled:     true
  collections: false

