title: Meru Data
email: info@merudata.com
url: ""
twitter_username: merudata
github_username:  merudata
baseurl: "/docs"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-relative-links
relative_links:
  enabled:     true
  collections: false

